/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssetBreakdown {
  'asset' : string,
  'trades' : bigint,
  'totalPnl' : number,
  'winRate' : number,
}
export interface MonthlyPnl {
  'pnl' : number,
  'month' : bigint,
  'year' : bigint,
}
export type Time = bigint;
export interface Trade {
  'id' : bigint,
  'pnl' : number,
  'asset' : string,
  'tradeType' : string,
  'date' : Time,
  'lots' : number,
  'notes' : string,
  'entryPrice' : number,
  'exitPrice' : number,
  'lotSize' : number,
}
export interface TradeInput {
  'asset' : string,
  'tradeType' : string,
  'date' : Time,
  'lots' : number,
  'notes' : string,
  'entryPrice' : number,
  'exitPrice' : number,
  'lotSize' : number,
}
export interface TradeStats {
  'bestTrade' : number,
  'worstTrade' : number,
  'totalTrades' : bigint,
  'totalLoss' : number,
  'netPnl' : number,
  'avgLoss' : number,
  'totalProfit' : number,
  'winRate' : number,
  'avgProfit' : number,
}
export interface _SERVICE {
  'addTrade' : ActorMethod<[TradeInput], bigint>,
  'deleteTrade' : ActorMethod<[bigint], undefined>,
  'getAssetBreakdown' : ActorMethod<[], Array<AssetBreakdown>>,
  'getMonthlyPnl' : ActorMethod<[], Array<MonthlyPnl>>,
  'getStats' : ActorMethod<[], TradeStats>,
  'getTrades' : ActorMethod<[], Array<Trade>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];