/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const TradeInput = IDL.Record({
  'asset' : IDL.Text,
  'tradeType' : IDL.Text,
  'date' : Time,
  'lots' : IDL.Float64,
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
  'lotSize' : IDL.Float64,
});
export const AssetBreakdown = IDL.Record({
  'asset' : IDL.Text,
  'trades' : IDL.Nat,
  'totalPnl' : IDL.Float64,
  'winRate' : IDL.Float64,
});
export const MonthlyPnl = IDL.Record({
  'pnl' : IDL.Float64,
  'month' : IDL.Nat,
  'year' : IDL.Int,
});
export const TradeStats = IDL.Record({
  'bestTrade' : IDL.Float64,
  'worstTrade' : IDL.Float64,
  'totalTrades' : IDL.Nat,
  'totalLoss' : IDL.Float64,
  'netPnl' : IDL.Float64,
  'avgLoss' : IDL.Float64,
  'totalProfit' : IDL.Float64,
  'winRate' : IDL.Float64,
  'avgProfit' : IDL.Float64,
});
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Float64,
  'asset' : IDL.Text,
  'tradeType' : IDL.Text,
  'date' : Time,
  'lots' : IDL.Float64,
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
  'lotSize' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addTrade' : IDL.Func([TradeInput], [IDL.Nat], []),
  'deleteTrade' : IDL.Func([IDL.Nat], [], []),
  'getAssetBreakdown' : IDL.Func([], [IDL.Vec(AssetBreakdown)], ['query']),
  'getMonthlyPnl' : IDL.Func([], [IDL.Vec(MonthlyPnl)], ['query']),
  'getStats' : IDL.Func([], [TradeStats], ['query']),
  'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const TradeInput = IDL.Record({
    'asset' : IDL.Text,
    'tradeType' : IDL.Text,
    'date' : Time,
    'lots' : IDL.Float64,
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
    'lotSize' : IDL.Float64,
  });
  const AssetBreakdown = IDL.Record({
    'asset' : IDL.Text,
    'trades' : IDL.Nat,
    'totalPnl' : IDL.Float64,
    'winRate' : IDL.Float64,
  });
  const MonthlyPnl = IDL.Record({
    'pnl' : IDL.Float64,
    'month' : IDL.Nat,
    'year' : IDL.Int,
  });
  const TradeStats = IDL.Record({
    'bestTrade' : IDL.Float64,
    'worstTrade' : IDL.Float64,
    'totalTrades' : IDL.Nat,
    'totalLoss' : IDL.Float64,
    'netPnl' : IDL.Float64,
    'avgLoss' : IDL.Float64,
    'totalProfit' : IDL.Float64,
    'winRate' : IDL.Float64,
    'avgProfit' : IDL.Float64,
  });
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Float64,
    'asset' : IDL.Text,
    'tradeType' : IDL.Text,
    'date' : Time,
    'lots' : IDL.Float64,
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
    'lotSize' : IDL.Float64,
  });
  
  return IDL.Service({
    'addTrade' : IDL.Func([TradeInput], [IDL.Nat], []),
    'deleteTrade' : IDL.Func([IDL.Nat], [], []),
    'getAssetBreakdown' : IDL.Func([], [IDL.Vec(AssetBreakdown)], ['query']),
    'getMonthlyPnl' : IDL.Func([], [IDL.Vec(MonthlyPnl)], ['query']),
    'getStats' : IDL.Func([], [TradeStats], ['query']),
    'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };